// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD56Y0mHgQzgYhq07PDjSVCdcBXHt_kYiU',
    appId: '1:7860040973:web:cc28ad0b24d95935c7ec44',
    messagingSenderId: '7860040973',
    projectId: 'youmart-app-test',
    authDomain: 'youmart-app-test.firebaseapp.com',
    storageBucket: 'youmart-app-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCmpJ_Q33wB19r46sYMh5qCvnASHRr8s',
    appId: '1:7860040973:android:ffdf66205ccdc514c7ec44',
    messagingSenderId: '7860040973',
    projectId: 'youmart-app-test',
    storageBucket: 'youmart-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiywh0fhBrqKUxSq7wwyRX7UQISUMvTgU',
    appId: '1:7860040973:ios:788387a0cdb4d15ac7ec44',
    messagingSenderId: '7860040973',
    projectId: 'youmart-app-test',
    storageBucket: 'youmart-app-test.appspot.com',
    iosClientId: '7860040973-roomd4l0u52hdsbf1m90vp2nuifg055t.apps.googleusercontent.com',
    iosBundleId: 'com.example.youmartMobitech',
  );
}
